### ISSUE TITLE
Uncaught TypeError: Cannot read property 'item' of undefined

### ISSUE THREAD

**Issue by rclai** [georgebrindeiro/scroll-sync#12]
**Edit**: Whoops sorry for the multiple issue posts, the're probably the same.
1. Press Ctrl + Alt + S

**Atom Version**: 1.0.5
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [scroll-sync](https://github.com/mark-hahn/scroll-sync) package, v0.1.4
### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At C:\Users\richardl\.atom\packages\scroll-sync\lib\scroll-sync.coffee:34

TypeError: Cannot read property 'item' of undefined
  at ScrlSync.startTracking (C:\Users\richardl\.atom\packages\scroll-sync\lib\scroll-sync.coffee:34:19)
  at atom-workspace.subToggle.add.atom.commands.add.scroll-sync:toggle (C:\Users\richardl\.atom\packages\scroll-sync\lib\scroll-sync.coffee:19:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\richardl\AppData\Local\atom\app-1.0.5\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\richardl\AppData\Local\atom\app-1.0.5\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\richardl\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\richardl\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\richardl\AppData\Local\atom\app-1.0.5\resources\app.asar\src\window-event-handler.js:177:20)

```
### Commands

```
  2x -7:05.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -7:04.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:59.7.0 core:copy (atom-text-editor.editor.is-focused)
     -6:59.2.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -6:59 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:58.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -6:57.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:38.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:37.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -5:35.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:32.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -5:27.5.0 core:save (atom-text-editor.editor.is-focused)
     -5:08.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -4:49.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -4:46.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.2.0 scroll-sync:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.10
color-picker, v2.0.11
emmet, v2.3.12
language-batch, v0.3.3
minimap, v4.12.2
node-debugger, vundefined
remote-edit, v1.8.14
scroll-sync, v0.1.4

# Dev
No dev packages
```

**Comment by KathrynCrawford** [comment]
Same issue

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [scroll-sync](https://github.com/mark-hahn/scroll-sync) package, v0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /Users/kathryn.crawford/.atom/packages/scroll-sync/lib/scroll-sync.coffee:34

TypeError: Cannot read property 'item' of undefined
  at ScrlSync.startTracking (/Users/kathryn.crawford/.atom/packages/scroll-sync/lib/scroll-sync.coffee:34:19)
  at atom-workspace.subToggle.add.atom.commands.add.scroll-sync:toggle (/Users/kathryn.crawford/.atom/packages/scroll-sync/lib/scroll-sync.coffee:19:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -7:53.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:48 window:save-all (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
 10x -1:22 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:17.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.0 scroll-sync:toggle (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
clipboard-history, v0.6.6
compare-files, v0.6.2
scroll-sync, v0.1.4

# Dev
No dev packages
```

**Comment by VincentGuinaudeau** [comment]
Same issue

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [scroll-sync](https://github.com/mark-hahn/scroll-sync) package, v0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /C:/Users/vguinaudeau/.atom/packages/scroll-sync/lib/scroll-sync.coffee:62

TypeError: Cannot read property 'item' of undefined
  at ScrlSync.startTracking (C:\Users\vguinaudeau\.atom\packages\scroll-sync\lib\scroll-sync.coffee:34:19)
  at atom-workspace.subToggle.add.atom.commands.add.scroll-sync:toggle (C:\Users\vguinaudeau\.atom\packages\scroll-sync\lib\scroll-sync.coffee:19:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\vguinaudeau\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\vguinaudeau\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\vguinaudeau\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\vguinaudeau\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\vguinaudeau\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:184:20)

```

### Commands

```
     -3:44 atom-beautify:beautify-editor (atom-text-editor.editor)
  2x -2:07.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:50.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:48.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:46.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:46.4.0 atom-beautify:beautify-editor (atom-text-editor.editor)
  4x -1:34.8.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -1:28.4.0 core:backspace (atom-text-editor.editor.is-focused)
  6x -1:26.6.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -1:18.6.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -1:17.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:02.8.0 pane:split-right (atom-text-editor.editor.is-focused)
     -0:47.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:13 core:cancel (atom-text-editor.editor.is-focused)
     -0:10.7.0 scroll-sync:toggle (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-seti"
    ],
    "disabledPackages": [
      "autoflow",
      "metrics",
      "wrap-guide",
      "welcome",
      "file-icons",
      "hex"
    ],
    "autoHideMenuBar": true,
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.28.14
color-tabs, v0.1.8
fonts, v0.7.0
highlight-selected, v0.10.1
keyboard-localization, v1.4.9
linter, v1.9.0
linter-jshint, v1.2.1
minimap, v4.15.0
minimap-autohide, v0.10.1
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
monokai-seti, v0.7.0
open-recent, v2.3.0
project-manager, v2.6.5
remote-edit, v1.8.21
scroll-sync, v0.1.4
seti-ui, v0.8.0

# Dev
No dev packages
```

**Comment by richardchaffer** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.2
**Thrown From**: [scroll-sync](https://github.com/mark-hahn/scroll-sync) package, v0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /Users/mac_user/.atom/packages/scroll-sync/lib/scroll-sync.coffee:34

TypeError: Cannot read property 'item' of undefined
    at ScrlSync.startTracking (/Users/mac_user/.atom/packages/scroll-sync/lib/scroll-sync.coffee:34:19)
    at atom-workspace.subToggle.add.atom.commands.add.scroll-sync:toggle (/Users/mac_user/.atom/packages/scroll-sync/lib/scroll-sync.coffee:19:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -7:07.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -7:04.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:56 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -6:55.4.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -6:54.9.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -6:53.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -6:49.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:41.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 12x -6:39 core:move-left (atom-text-editor.editor.is-focused)
 10x -6:36.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:27.8.0 core:save (atom-text-editor.editor.is-focused)
     -6:26.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -6:24.8.0 core:close (atom-text-editor.editor.is-focused)
     -0:10.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:07.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.7.0 scroll-sync:toggle (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".DS_Store"
    ],
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "shadow",
      "shadow",
      "shadow"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
advanced-open-file, vundefined
atom-beautify, v0.28.19
auto-indent, v0.5.0
browser-plus, v0.0.54
color-picker, v2.0.14
compare-files, v0.6.2
highlight-selected, v0.11.1
indentation-indicator, v0.6.0
language-haml, v0.23.14
linter-haml, v1.0.0
mixed-indent-warning, v0.3.0
monokai, v0.18.0
php-cs-fixer, v2.5.1
pretty-json, v0.4.1
scroll-sync, v0.1.4
simple-drag-drop-text, v0.3.0
space-tab, v0.4.2
split-diff, v0.5.0
symbol-gen, v1.0.0
webbox-color, vundefined

# Dev
No dev packages
```

**Comment by Braunson** [comment]
[Enter steps to reproduce below:]
1. Right click and clicking 'Toggle Scroll Sync'

**Atom Version**: 1.3.2
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: [scroll-sync](https://github.com/mark-hahn/scroll-sync) package, v0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /C:/Users/geekybeaver/.atom/packages/scroll-sync/lib/scroll-sync.coffee:62

TypeError: Cannot read property 'item' of undefined
    at ScrlSync.startTracking (file:///C:/Users/geekybeaver/.atom/packages/scroll-sync/lib/scroll-sync.coffee:34:19)
    at atom-workspace.subToggle.add.atom.commands.add.scroll-sync:toggle (file:///C:/Users/geekybeaver/.atom/packages/scroll-sync/lib/scroll-sync.coffee:19:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\geekybeaver\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\geekybeaver\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\geekybeaver\AppData\Local\atom\app-1.3.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\geekybeaver\AppData\Local\atom\app-1.3.2\resources\app.asar\src\atom-environment.js:1016:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (C:\Users\geekybeaver\AppData\Local\atom\app-1.3.2\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\geekybeaver\AppData\Local\atom\app-1.3.2\resources\atom.asar\renderer\api\lib\remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\geekybeaver\AppData\Local\atom\app-1.3.2\resources\app.asar\src\context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (C:\Users\geekybeaver\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (C:\Users\geekybeaver\AppData\Local\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -4:39.3.0 core:save (atom-text-editor.editor.is-focused)
     -3:53.8.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:42.4.0 core:close (atom-text-editor.editor.is-focused)
     -3:34.9.0 tree-view:open-selected-entry-right (span.name.icon.icon-file-text)
     -1:51.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:49.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:49.7.0 settings-view:open (atom-text-editor.editor)
  2x -1:40.6.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:38.6.0 core:cut (atom-text-editor.editor.mini.is-focused)
     -0:44.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:44.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.5.0 core:close (div.package-detail.panels-item)
     -0:19.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:19.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:19.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:10.8.0 scroll-sync:toggle (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "autocomplete-paths",
      "atom-beautify"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
aligner, v0.17.4
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-scss, v1.1.0
angularjs, v0.3.3
atom-shortcuts, v0.0.2
autocomplete-php, v0.3.7
color-picker, v2.0.14
devdocs, v0.2.1
docblockr, v0.7.3
file-icons, v1.6.13
highlight-line, v0.11.0
highlight-selected, v0.11.1
jshint, v1.8.3
language-sql-mysql, v0.3.1
laravel, v0.7.0
linter, v1.11.3
linter-php, v1.1.6
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
php-cs-fixer, v2.5.1
pigments, v0.19.5
Remote-FTP, v0.7.15
scroll-sync, v0.1.4
tabs-to-spaces, v1.0.1
tree-view-git-modified, v0.6.0

# Dev
No dev packages
```

**Comment by ryanjbonnell** [comment]
I get the same error message when trying to enable [sync-scroll](https://github.com/mark-hahn/scroll-sync/) 0.1.4:

> **Uncaught TypeError: Cannot read property 'item' of undefined**
> ~/.atom/packages/scroll-sync/lib/scroll-sync.coffee:34

Using Atom 1.3.3 on Mac OS X 10.11.2 "El Capitan".

**Comment by trjones1** [comment]
:+1:  Same Issue:
1. Hit Ctrl Alt S or toggle scrollsync

**Atom Version**: 1.4.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [scroll-sync](https://github.com/mark-hahn/scroll-sync) package, v0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /C:/Users/tramel/.atom/packages/scroll-sync/lib/scroll-sync.coffee:62

TypeError: Cannot read property 'item' of undefined
    at ScrlSync.startTracking (file:///C:/Users/tramel/.atom/packages/scroll-sync/lib/scroll-sync.coffee:34:19)
    at atom-workspace.subToggle.add.atom.commands.add.scroll-sync:toggle (file:///C:/Users/tramel/.atom/packages/scroll-sync/lib/scroll-sync.coffee:19:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\tramel\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\tramel\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\tramel\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\tramel\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\tramel\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\tramel\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\tramel\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\tramel\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\tramel\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\tramel\AppData\Local\atom\app-1.4.0\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\tramel\AppData\Local\atom\app-1.4.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -1:36.4.0 tabs:split-right (div.title)
     -1:09.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -1:06.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:03.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:03.0 scroll-sync:toggle (atom-text-editor.editor)
  2x -0:07.5.0 core:cancel (a.btn-copy-report.icon.icon-clippy)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "steam-pirate-ui",
      "octocat-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
color-picker, v2.0.14
git-status, v0.3.4
keyboard-scroll, v0.4.0
language-asp, v1.0.0
language-aspx, v0.4.0
language-vb, v0.1.0-pre1
minimap, v4.19.0
minimap-codeglance, v0.4.5
octocat-syntax, v0.1.5
scroll-sync, v0.1.4
steam-pirate-ui, v0.6.1

# Dev
No dev packages
```

**Comment by lacostenycoder** [comment]
- 1 same problem

[Enter steps to reproduce below:]
1. have two unsaved text files opened in split view
2. enable scroll lock

**Atom Version**: 1.4.0
**System**: Mac OS X 10.9.4
**Thrown From**: [scroll-sync](https://github.com/mark-hahn/scroll-sync) package, v0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /Users/lancejordan/.atom/packages/scroll-sync/lib/scroll-sync.coffee:34

TypeError: Cannot read property 'item' of undefined
    at ScrlSync.startTracking (/Users/lancejordan/.atom/packages/scroll-sync/lib/scroll-sync.coffee:34:19)
    at atom-workspace.subToggle.add.atom.commands.add.scroll-sync:toggle (/Users/lancejordan/.atom/packages/scroll-sync/lib/scroll-sync.coffee:19:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -1:43.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:43.2.0 blur (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:42.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:42.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:42.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -1:41.3.0 application:new-file (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  9x -1:41.3.0 blur (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -1:37.6.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  8x -1:36 blur (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:34.5.0 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:32.9.0 blur (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:32.8.0 grammar-selector:show (atom-text-editor.editor.vim-mode.insert-mode)
     -0:32.8.0 blur (a.inline-block)
     -0:31.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:31.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:10.1.0 scroll-sync:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "jslint",
      "sass-autocompile",
      "highlight-line"
    ],
    "ignoredNames": [
      "metronic/**"
    ],
    "themes": [
      "atom-dark-ui",
      "steam-pirate-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.28.21
atom-erb, v0.2.0
atom-minify, v0.7.1
color-picker, v2.0.14
emmet, v2.3.18
glowing-cursor, v0.1.1
html2haml, v0.10.0
language-ejs, v0.2.0
language-gherkin, v1.0.3
language-haml, v0.23.14
language-jade, v0.6.2
linter, v1.11.3
linter-bootlint, v1.0.0
rails-partials, v0.8.1
ruby-block, v0.3.5
scroll-sync, v0.1.4
selector-to-tag, v0.4.1
slim-language, v2.2.0
steam-pirate-syntax, v0.3.0
tag, v0.3.0
toggle-packages, v1.1.0
vim-mode, v0.64.0
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by RafaelKr** [comment]
Edit: I had the same issue, now i replaced the /lib/scroll-sync.coffee with the fixed one, but now i don't get it to work. ScrlSync shows up in statusbar, but it only scrolls one Pane.

**Comment by emilbayes** [comment]
This issue still seems to be present at times. When I succeed at enabeling scroll sync, scrolling one pane sends the other to the end of the file.

---

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [scroll-sync](https://github.com/mark-hahn/scroll-sync) package, v0.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /Users/emil/.atom/packages/scroll-sync/lib/scroll-sync.coffee:34

TypeError: Cannot read property 'item' of undefined
    at ScrlSync.startTracking (/Users/emil/.atom/packages/scroll-sync/lib/scroll-sync.coffee:34:19)
    at atom-workspace.subToggle.add.atom.commands.add.scroll-sync:toggle (/Users/emil/.atom/packages/scroll-sync/lib/scroll-sync.coffee:19:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:06.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:04.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.8.0 scroll-sync:toggle (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "autocomplete-elixir",
      "language-elixir",
      "elixir-cmd"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
docblockr, v0.7.3
editor-stats, v0.17.0
editorconfig, v1.2.4
emmet, v2.4.1
language-cypher, v0.3.0
language-docker, v1.1.6
language-elm, v1.3.2
language-ini, v1.14.0
language-julia, v0.9.0
language-latex, v0.6.1
language-nginx, v0.6.1
language-pgsql, v0.2.0
latex, v0.29.0
linter, v1.11.3
linter-elm-make, v0.4.0
linter-js-standard, v3.2.1
linter-jsonlint, v1.1.5
linter-php, v1.1.8
markdown-table-formatter, v2.7.2
new-file-plus, v0.2.1
pigments, v0.24.1
pretty-json, v0.4.1
scroll-sync, v0.1.4
standard-formatter, v2.0.0
synced-sidebar, v0.4.3
travis-ci-status, v1.0.0
zentabs, v0.8.7

# Dev
No dev packages
```
