### ISSUE TITLE
Error: Cannot find module 'diff_match_patch'

### ISSUE THREAD

**Issue by kirschkern** [georgebrindeiro/scroll-sync#32]
I downloaded the zip file and placed its content into my atom/packages/ directory. After restarting Atom I get this error Error: Cannot find module 'diff_match_patch'

The menu entry "Toggle Scroll Sync" in the "Packages" menu is available but selecting it doesn't change anything. I don't see the arrows and the shortcut doesn't work as well.

Here is the error report.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: DESKTOP-9JSVPGG
**Thrown From**: [scroll-sync-master](https://github.com/georgebrindeiro/scroll-sync) package 0.2.4

### Stack Trace

Failed to load the scroll-sync-master package

```
At Cannot find module 'diff_match_patch'

Error: Cannot find module 'diff_match_patch'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.24.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.24.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.24.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/scroll-sync-master/lib/scroll-sync.coffee:3:11)
    at /packages/scroll-sync-master/lib/scroll-sync.coffee:2:1)
    at /packages/scroll-sync-master/lib/scroll-sync.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.24.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.24.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.24.0/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:782:33)
    at measure (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:143:22)
    at Package.measure (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:88:25)
    at Package.load (~/AppData/Local/atom/app-1.24.0/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:618:16)
    at config.transact (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (~/AppData/Local/atom/app-1.24.0/resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.24.0/resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.24.0/resources/app/src/atom-environment.js:818:27)
```

**Comment by georgebrindeiro-vtex** [comment]
Hi @kirschkern. That isn't the usual installation route for Atom packages. My guess is that you're missing a dependency that would've been installed automatically by apm. 

You can find the latest version of this package by searching directly in Atom (File -> Settings -> Install). Have you tried that? Sorry for taking so long to answer.

**Comment by kirschkern** [comment]
Works. Thanks!
