### ISSUE TITLE
Failed to load the scroll-sync package

### ISSUE THREAD

**Issue by fbbdev** [georgebrindeiro/scroll-sync#4]
Steps to reproduce:
1. Install atom 0.190.0
2. Install scroll-sync package
3. Run atom in 1.0 API mode: `atom -1`

**Atom Version**: 0.190.0
**System**: linux 3.19.3-200.fc21.x86_64
**Thrown From**: [scroll-sync](https://github.com/mark-hahn/scroll-sync) package, v0.1.1
### Stack Trace

Failed to load the scroll-sync package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/home/fabio/.atom/packages/scroll-sync/lib/status-bar-view.coffee:4:199)
  at /home/fabio/.atom/packages/scroll-sync/lib/status-bar-view.coffee:5:3
  at Object.<anonymous> (/home/fabio/.atom/packages/scroll-sync/lib/status-bar-view.coffee:47:5)
  at Object.<anonymous> (/home/fabio/.atom/packages/scroll-sync/lib/status-bar-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/fabio/.atom/packages/scroll-sync/lib/scroll-sync.coffee:3:17)
  at Object.<anonymous> (/home/fabio/.atom/packages/scroll-sync/lib/scroll-sync.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:665:34)
  at /usr/share/atom/resources/app/src/package.js:174:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:152:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:166:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:355:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:325:14)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:631:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:54:25)

```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-bibtex, v0.5.6
autocomplete-css, v0.6.0
autocomplete-glsl, v0.2.0
autocomplete-haskell, v0.2.1
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.9.0
autocomplete-plus-jedi, v0.0.9
bezier-curve-editor, v0.6.6
color-picker, v1.6.0
fancy-new-file, v0.7.0
format-sql, v0.2.0
git-blame, v0.4.0
git-history, v2.5.0
git-log, v0.3.0
highlight-line, v0.10.1
linter, v0.12.0
linter-clang, v2.25.1
linter-javac, v0.1.3
linter-js-yaml, v1.0.0
linter-python-pep8, v0.2.0
minimap, v4.7.6
minimap-git-diff, v4.1.2
ogg-preview, v0.2.0
pdf-view, v0.17.0
project-manager, v1.15.5
quick-move-file, v0.7.0
scroll-sync, v0.1.1
svg-preview, v0.5.1
task-list, v0.7.0

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
I can't reproduce this in Atom 201, can you?

**Comment by fbbdev** [comment]
It's not happening anymore in atom 0.201
