### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by j2bradley** [georgebrindeiro/scroll-sync#7]
I am not sure why this error happened. I had several files open in two panes, and was using this package to view to similar files. I left to do some work on the command line (updated and rebuilt libMesh) and when I came back I found this error.

**Atom Version**: 0.205.0
**System**: Mac OS X 10.10.3
**Thrown From**: [scroll-sync](https://github.com/mark-hahn/scroll-sync) package, v0.1.3
### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:128

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1040:15)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToBufferPosition (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:684:47)
  at TextEditor.module.exports.TextEditor.scrollToBufferPosition (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2505:33)
  at ScrlSync.scrollPosChanged (/Users/bradjh/.atom/packages/scroll-sync/lib/scroll-sync.coffee:116:19)
  at /Users/bradjh/.atom/packages/scroll-sync/lib/scroll-sync.coffee:76:64
  at Emitter.module.exports.Emitter.emit (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:119:32
  at Emitter.module.exports.Emitter.emit (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.setScrollTop (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:470:22)
  at DisplayBuffer.module.exports.DisplayBuffer.setScrollBottom (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:484:12)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToScreenRange (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:652:16)
  at TextEditor.module.exports.TextEditor.scrollToScreenRange (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2521:33)
  at Cursor.module.exports.Cursor.autoscroll (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/cursor.js:700:26)
  at Cursor.module.exports.Cursor.changePosition (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/cursor.js:685:21)
  at Cursor.module.exports.Cursor.setBufferPosition (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/cursor.js:134:19)
  at /Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1325:23
  at TextEditor.module.exports.TextEditor.moveCursors (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1546:9)
  at TextEditor.module.exports.TextEditor.setCursorBufferPosition (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1324:19)
  at /Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1584:19
  at Emitter.module.exports.Emitter.emit (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.reload (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1047:20)
  at /Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1169:26
  at Emitter.module.exports.Emitter.emit (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:430:40
  at _fulfilled (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Users/bradjh/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```
### Commands

```
  3x -8:33.3.0 switch-header-source:switch (atom-text-editor.editor.is-focused)
     -7:23.2.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui.find-visible)
     -6:21.1.0 scroll-sync:toggle (atom-text-editor.editor.is-focused)
     -5:00.1.0 core:delete (atom-text-editor.editor.is-focused)
     -4:48.5.0 core:paste (atom-text-editor.editor.is-focused)
  2x -4:46 core:save (atom-text-editor.editor.is-focused)
 10x -3:08.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:00.2.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
git-diff-details, v0.18.0
language-moose, v0.12.0
scroll-sync, v0.1.3
switch-header-source, v0.16.0

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
I have seen this error repeated since before I wrote any packages.  I
posted an issue at atom/atom last year.  I'll look up that issue.

**Comment by mark-hahn** [comment]
See https://github.com/atom/atom/issues/4562
